
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geivgrieaxvwgfvuicrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlaXZncmllYXh2d2dmdnVpY3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzYwMDIsImV4cCI6MjA2MTg1MjAwMn0.GbdDPmhKnm6qIR-GvVIDC-YRK5w5pZOc0PoGjUNloUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
